name = "chord_sim"
version = "1.0.0"

# Project dependencies
[dependencies]
gleam_stdlib = ">= 0.63.2 and < 1.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_otp = ">= 1.1.0 and < 2.0.0"
gleam_time = ">= 1.4.0 and < 2.0.0"
randomlib = "1.1.2"
input = ">= 1.0.1 and < 2.0.0"

# Development-only dependencies
[dev-dependencies]
gleeunit = ">= 0.10.0 and < 2.0.0"

# Executable configuration
[executable]
main = "main"
